//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobiWinClient.SystemUserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://schemas.datacontract.org/2004/07/Core")]
    [System.SerializableAttribute()]
    public partial class SystemUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NobiWinClient.SystemUserService.Role RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NobiWinClient.SystemUserService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Core")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemUserService.ISystemUserService")]
    public interface ISystemUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/All", ReplyAction="http://tempuri.org/ISystemUserService/AllResponse")]
        NobiWinClient.SystemUserService.SystemUser[] All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/All", ReplyAction="http://tempuri.org/ISystemUserService/AllResponse")]
        System.Threading.Tasks.Task<NobiWinClient.SystemUserService.SystemUser[]> AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Create", ReplyAction="http://tempuri.org/ISystemUserService/CreateResponse")]
        void Create(NobiWinClient.SystemUserService.SystemUser entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Create", ReplyAction="http://tempuri.org/ISystemUserService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(NobiWinClient.SystemUserService.SystemUser entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Read", ReplyAction="http://tempuri.org/ISystemUserService/ReadResponse")]
        NobiWinClient.SystemUserService.SystemUser Read(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Read", ReplyAction="http://tempuri.org/ISystemUserService/ReadResponse")]
        System.Threading.Tasks.Task<NobiWinClient.SystemUserService.SystemUser> ReadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Update", ReplyAction="http://tempuri.org/ISystemUserService/UpdateResponse")]
        void Update(NobiWinClient.SystemUserService.SystemUser entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Update", ReplyAction="http://tempuri.org/ISystemUserService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(NobiWinClient.SystemUserService.SystemUser entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Delete", ReplyAction="http://tempuri.org/ISystemUserService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemUserService/Delete", ReplyAction="http://tempuri.org/ISystemUserService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemUserServiceChannel : NobiWinClient.SystemUserService.ISystemUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemUserServiceClient : System.ServiceModel.ClientBase<NobiWinClient.SystemUserService.ISystemUserService>, NobiWinClient.SystemUserService.ISystemUserService {
        
        public SystemUserServiceClient() {
        }
        
        public SystemUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NobiWinClient.SystemUserService.SystemUser[] All() {
            return base.Channel.All();
        }
        
        public System.Threading.Tasks.Task<NobiWinClient.SystemUserService.SystemUser[]> AllAsync() {
            return base.Channel.AllAsync();
        }
        
        public void Create(NobiWinClient.SystemUserService.SystemUser entity) {
            base.Channel.Create(entity);
        }
        
        public System.Threading.Tasks.Task CreateAsync(NobiWinClient.SystemUserService.SystemUser entity) {
            return base.Channel.CreateAsync(entity);
        }
        
        public NobiWinClient.SystemUserService.SystemUser Read(int id) {
            return base.Channel.Read(id);
        }
        
        public System.Threading.Tasks.Task<NobiWinClient.SystemUserService.SystemUser> ReadAsync(int id) {
            return base.Channel.ReadAsync(id);
        }
        
        public void Update(NobiWinClient.SystemUserService.SystemUser entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(NobiWinClient.SystemUserService.SystemUser entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
